//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basvuru_durumu
    {
        public basvuru_durumu()
        {
            this.basvurular = new HashSet<basvurular>();
        }
    
        public int BDurumID { get; set; }
        public string BDurum { get; set; }
    
        public virtual ICollection<basvurular> basvurular { get; set; }
    }
}
