//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class byabancidil
    {
        public int BYDilID { get; set; }
        public Nullable<int> DilID { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<int> BasSeviyeID { get; set; }
    
        public virtual basari_seviyeleri basari_seviyeleri { get; set; }
        public virtual diller diller { get; set; }
        public virtual basvurular basvurular { get; set; }
    }
}
