//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deneyim
    {
        public int DeneyimID { get; set; }
        public Nullable<System.DateTime> BaslamaTar { get; set; }
        public Nullable<System.DateTime> BitisTar { get; set; }
        public string FirmaAdi { get; set; }
        public Nullable<int> IlID { get; set; }
        public string IsTanimi { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<int> MeslekID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual meslekler meslekler { get; set; }
        public virtual basvurular basvurular { get; set; }
    }
}
