//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diller
    {
        public diller()
        {
            this.byabancidil = new HashSet<byabancidil>();
        }
    
        public int DilID { get; set; }
        public string DilAdi { get; set; }
    
        public virtual ICollection<byabancidil> byabancidil { get; set; }
    }
}
