//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fakulteler
    {
        public fakulteler()
        {
            this.bolumler = new HashSet<bolumler>();
        }
    
        public int fakulte_id { get; set; }
        public string fakulte_ad { get; set; }
        public int uni_id { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<bolumler> bolumler { get; set; }
        public virtual universiteler universiteler { get; set; }
    }
}
