//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilceler
    {
        public ilceler()
        {
            this.kullanicilar = new HashSet<kullanicilar>();
        }
    
        public int IlceID { get; set; }
        public string Ilce { get; set; }
        public Nullable<int> IlID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual ICollection<kullanicilar> kullanicilar { get; set; }
    }
}
