//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iller
    {
        public iller()
        {
            this.ilceler = new HashSet<ilceler>();
            this.universiteler = new HashSet<universiteler>();
            this.deneyim = new HashSet<deneyim>();
        }
    
        public int IlID { get; set; }
        public string Il { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<ilceler> ilceler { get; set; }
        public virtual ICollection<universiteler> universiteler { get; set; }
        public virtual ICollection<deneyim> deneyim { get; set; }
    }
}
