//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public kullanicilar()
        {
            this.basvurular = new HashSet<basvurular>();
        }
    
        public int KID { get; set; }
        public string KAdi { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public string KSoyad { get; set; }
        public string KEposta { get; set; }
        public string KSifre { get; set; }
        public Nullable<System.DateTime> KDogTar { get; set; }
        public string KTelNo { get; set; }
        public string KIban { get; set; }
        public Nullable<bool> KCinsiyet { get; set; }
        public string KResim { get; set; }
        public Nullable<int> IlceID { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        public virtual yetkiler yetkiler { get; set; }
        public virtual ICollection<basvurular> basvurular { get; set; }
    }
}
