//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeler
    {
        public int ProjeID { get; set; }
        public string ProjeAdi { get; set; }
        public string Proje_Aciklama { get; set; }
        public Nullable<int> BID { get; set; }
    
        public virtual basvurular basvurular { get; set; }
    }
}
