//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referanslar
    {
        public int RefID { get; set; }
        public string RefAdi { get; set; }
        public string RefSoyad { get; set; }
        public string RefMail { get; set; }
        public string RefTel { get; set; }
        public Nullable<int> BID { get; set; }
    
        public virtual basvurular basvurular { get; set; }
    }
}
