//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sem_kurs
    {
        public int SKID { get; set; }
        public string EgitimAdi { get; set; }
        public string Egitim_Kurumu { get; set; }
        public string Egitmen_Adi { get; set; }
        public string Egitmen_Soyadi { get; set; }
        public Nullable<System.DateTime> Bas_Tar { get; set; }
        public Nullable<System.DateTime> Bitis_Tar { get; set; }
        public Nullable<int> BID { get; set; }
    
        public virtual basvurular basvurular { get; set; }
    }
}
