//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sertifikalar
    {
        public int SertifikaID { get; set; }
        public string SertifikaAdi { get; set; }
        public string Alindigi_Kurum { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<System.DateTime> AlimTar { get; set; }
        public string SertifikaPDF { get; set; }
    
        public virtual basvurular basvurular { get; set; }
    }
}
