//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class universiteler
    {
        public universiteler()
        {
            this.fakulteler = new HashSet<fakulteler>();
        }
    
        public int uni_id { get; set; }
        public string uni_name { get; set; }
        public int IlID { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<fakulteler> fakulteler { get; set; }
        public virtual iller iller { get; set; }
    }
}
