//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basvuru_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yetkiler
    {
        public yetkiler()
        {
            this.kullanicilar = new HashSet<kullanicilar>();
        }
    
        public int YetkiID { get; set; }
        public string Yetki { get; set; }
    
        public virtual ICollection<kullanicilar> kullanicilar { get; set; }
    }
}
